name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: takaheraw/mastodon
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: mastodon

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push app image to Amazon ECR
        id: build-app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecr-mastodon
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t mastodon ./mastodon/
          docker tag mastodon:latest $ECR_REGISTRY/$ECR_REPOSITORY:mastodon_latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:mastodon_latest
